# Generated by Django 5.0.7 on 2024-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_user_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user1',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user2',
            field=models.TextField(default='0'),
        ),
    ]
