# Generated by Django 5.0.7 on 2024-07-24 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_unique_together_alter_chatroom_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='0'),
        ),
    ]
