# Generated by Django 5.0.7 on 2024-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_room_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='encryption_key',
            field=models.IntegerField(default=15),
        ),
    ]
